name: Jenkins_trigger_build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: mickeygoussetorg/trigger-jenkins-job@v1
          with:
            jenkins-server:  "http://192.168.1.6:8080" # URL of the jenkins server. ex: http://myjenkins.acme.com:8080
            jenkins-job: "checklist" # The name of the jenkins job to run
            jenkins-username: Aishwarya 
            jenkins-pat: 11b4d62fe39ef109b948419b82b1871494 # personal Access token for accessing Jenkins
#             poll-time: 10 # how often (seconds) to poll the jenkins server for results
#             timeout-value: 600 # How long (seconds) to poll before timing out the action
#             verbose: true # true/false - turns on extra logging
#       uses: appleboy/jenkins-action@master
      
#       with:
#         url: "http://192.168.1.6:8080"
#         run: echo "url"
#         user: "Aishwarya"
#         token: 11b4d62fe39ef109b948419b82b1871494
#         job: "checklist"
