name: Jenkins_trigger_build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      run : echo "$(curl -X POST -u Aishwarya:11b4d62fe39ef109b948419b82b1871494 http://192.168.1.6:8080/job/checklist/build)"
#       uses: mickeygoussetorg/trigger-jenkins-job@v1
#       with:
#           jenkins-server: "http://192.168.1.6:8080"
#           jenkins-job: "checklist"
#           jenkins-username: "Aishwarya" 
#           jenkins-pat: "11b4d62fe39ef109b948419b82b1871494" 
#            
