name: Jenkins_trigger_build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      run : curl I -s -X POST -u Aishwarya:Dhumravarna@3343 http://192.168.1.6:8080/job/checklist/build
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
